name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to AWS EC2 (Using SSH)
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
          
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            # Stop and remove existing container
            docker stop flask_app || true
            docker rm flask_app || true
            
            # Remove old image
            docker rmi flask_app || true
            
            # Pull latest code
            cd ~/flask-app
            git pull origin main
            
            # Build new Docker image
            docker build -t flask_app .
            
            # Run the new container
            docker run -d -p 80:5000 --name flask_app flask_app
          EOF
